"""Añadir columna meet_link a Asesoria

Revision ID: 06fa900152f9
Revises: ceff55aba3b5
Create Date: 2024-12-08 19:50:18.357475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fa900152f9'
down_revision = 'ceff55aba3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asesoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meet_link', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asesoria', schema=None) as batch_op:
        batch_op.drop_column('meet_link')

    # ### end Alembic commands ###
