"""Add columns to User model

Revision ID: 564c9b8f236f
Revises: 
Create Date: 2024-10-12 19:02:29.458184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564c9b8f236f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('especializacion', sa.String(length=200), nullable=True),
    sa.Column('foto', sa.String(length=200), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
