"""Añadir columna total_pagado a Asesoria

Revision ID: ceff55aba3b5
Revises: 564c9b8f236f
Create Date: 2024-12-08 16:31:22.079373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceff55aba3b5'
down_revision = '564c9b8f236f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asesoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_pagado', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asesoria', schema=None) as batch_op:
        batch_op.drop_column('total_pagado')

    # ### end Alembic commands ###
